service: ddb-to-slack

provider:
  name: aws
  runtime: java11
  stage: prd
  region: us-east-1
  timeout: 20
  logRetentionInDays: 7
  iamManagedPolicies:
  - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'
  - 'arn:aws:iam::aws:policy/AmazonSSMFullAccess'
  - 'arn:aws:iam::aws:policy/AWSLambdaFullAccess'

package:
  artifact: build/libs/ddb-to-slack-prd-all.jar

functions:
  UserPropagationLambda:
    handler: com.budilov.data.DynamoDBStreamLambda
    memorySize: 1024
    events:
      - stream:
          arn: ${ssm:/ccPreregisterTableStreamArn}
          batchSize: 100
          startingPosition: LATEST
          maximumRetryAttempts: 10
    environment:
      slackEndpoint: ${ssm:/ccPreregisterSlackEndpoint}
